version: "3.1"

services:
  node:
    build: .
    image: custom_node
    ports:
      - 80:3000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - 27017:27017
  admin_mongo:
    image: mrvautin/adminmongo
    ports:
      - 1234:1234
